packaging_format = 2

id = "funkwhale"
name = "Funkwhale"
description.en = "Convivial and modern music server"
description.fr = "Serveur de musique moderne et convivial"

version = "1.4.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://funkwhale.audio/"
demo = "https://demo.funkwhale.audio"
admindoc = "https://docs.funkwhale.audio/admin/index.html"
userdoc = "https://docs.funkwhale.audio/users/index.html"
code = "https://dev.funkwhale.audio/funkwhale/funkwhale"
fund = "https://next.funkwhale.audio/donate/"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, Funkwhale will be accessible by Funkwhale for Android and by users without a YunoHost account. This can be changed later in the webadmin."
    help.fr = "Si cette case est cochée, Funkwhale sera accessible par Funkwhale for Android et par les utilisateurs n’ayant pas de compte YunoHost. Vous pourrez changer cela dans la webadmin."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources]
        [resources.sources.api]
        url = "https://dev.funkwhale.audio/funkwhale/funkwhale/-/jobs/artifacts/1.4.0/download?job=build_api"
        sha256 = "719c5cd0feb3716993d63bd09c05468615c0682c985c29f3be8076c2caa0e60f"
        in_subdir = true
        extract   = true
        format = "zip"

        [resources.sources.front]
        url = "https://dev.funkwhale.audio/funkwhale/funkwhale/-/jobs/artifacts/1.4.0/download?job=build_front"
        sha256 = "6df32113ca355e8181a463b2a83ef3eabf574a3faac16feb9d37a1f7844d0191"
        in_subdir = true
        extract   = true
        format = "zip"

        autoupdate.strategy = "latest_gitlab_release"
        autoupdate.asset.api = "api.*"
        autoupdate.asset.front = "front.*"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]
    
    [resources.data_dir]
    
    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "build-essential, curl, ffmpeg, libjpeg-dev, libmagic-dev, libpq-dev, postgresql, postgresql-client, postgresql-contrib, python3-dev, libldap2-dev, libsasl2-dev, make, unzip, zlib1g-dev, libffi-dev, libssl-dev, libxml2-dev, libxslt1-dev, libjpeg-dev, python3-venv, git"

    [resources.database]
    type = "postgresql"
