test_format = 1.0

[default]

    exclude = ["install.nourl"]

    test_upgrade_from.557386e0.name = "Upgrade from 1.2.7"
    test_upgrade_from.7a50028.name = "Upgrade from 1.2.9"
    test_upgrade_from.0373f8c.name = "Upgrade from 1.2.10~ynh1"
