test_format = 1.0

[default]

    test_upgrade_from.9058c1b.name = "1.3.1"
    test_upgrade_from.fefe575.name = "1.3.2"
    test_upgrade_from.13391bf.name = "1.3.3"
    test_upgrade_from.006a760.name = "1.3.4"

