test_format = 1.0

[default]

    exclude = ["install.nourl"]

    test_upgrade_from.7a50028.name = "1.2.9"
    test_upgrade_from.ae7b6c5.name = "1.2.10"
    test_upgrade_from.a5006b9.name = "1.3.0"

