#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --action="stop" --service_name="${app}-beat" --log_path="systemd" --line_match="Stopped"
ynh_systemd_action --action="stop" --service_name="${app}-server" --log_path="systemd" --line_match="Stopped"
ynh_systemd_action --action="stop" --service_name="${app}-worker" --log_path="systemd" --line_match="Stopped"

#=================================================
# MOVE DATAS
#=================================================

# If data_dir doesn't exist, create it
if [ -z "$data_dir" ]; then
	# Do a full backup before moving datas
	yunohost backup create --apps $app

	data_dir="/home/yunohost.app/${app}/data"
	ynh_script_progression --message="Moving datas to $data_dir..." --weight=1

	mkdir -p $data_dir
	mkdir -p $data_dir/{static,media,music}

	chmod 750 "$data_dir"
	chmod -R o-rwx "$data_dir"
	chown -R $app:www-data "$data_dir"
	
	ynh_backup_if_checksum_is_different --file="$install_dir/code/config/.env"
	mkdir -p $install_dir/config
	rsync -a $install_dir/code/config/ $install_dir/config/
	chmod 400 $install_dir/config/.env
	ynh_store_file_checksum --file="$install_dir/config/.env"
	ynh_delete_file_checksum --file="$install_dir/code/config/.env"
	
	if [ -d "$install_dir/code/data/static/" ]; then
		rsync -a $install_dir/code/data/static/ $data_dir/static/
	fi
	if [ -d "$install_dir/media/" ]; then
		rsync -a $install_dir/media/ $data_dir/media/
	fi
	if [ -d "$install_dir/code/data/media/" ]; then
		rsync -a $install_dir/code/data/media/ $data_dir/media/
	fi
	if [ -d "$install_dir/import/" ]; then
		rsync -a $install_dir/import/ $data_dir/music/
	fi
	if [ -d "$install_dir/code/data/music/" ]; then
		rsync -a $install_dir/code/data/music/ $data_dir/music/
	fi
	
#REMOVEME? 	ynh_secure_remove --file="$install_dir/code"
#REMOVEME? 	ynh_secure_remove --file="$install_dir/media"
#REMOVEME? 	ynh_secure_remove --file="$install_dir/code/data/media"
#REMOVEME? 	ynh_secure_remove --file="$install_dir/import"
#REMOVEME? 	ynh_secure_remove --file="$install_dir/code/data/music"

#REMOVEME? 	ynh_app_setting_set --app=$app --key=data_dir --value=$data_dir

	chmod 750 "$data_dir"
	chmod -R o-rwx "$data_dir"
	chown -R $app:www-data "$data_dir"
	
	upgrade_type="UPGRADE_APP"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=1

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir/api" --source_id="api"
	ynh_setup_source --dest_dir="$install_dir/front" --source_id="front"
fi

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading NGINX web server configuration..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing Python dependencies..." --weight=1

pushd $install_dir
ynh_secure_remove --file="$install_dir/virtualenv"
	python3 -m venv $install_dir/virtualenv
	source $install_dir/virtualenv/bin/activate
	pip install --upgrade pip
	pip install --upgrade setuptools
	ynh_exec_warn_less pip install wheel toml
	# Workaround for error AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
	ynh_replace_string --match_string="pyOpenSSL~=20.0.1" --replace_string="pyOpenSSL~=21.0.0" --target_file="$install_dir/api/requirements/base.txt"
	ynh_exec_warn_less pip install -r api/requirements.txt
popd

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..." --weight=1

ynh_add_config --template="../conf/env.prod" --destination="$install_dir/config/.env"

chmod 400 "$install_dir/config/.env"
chown $app:$app "$install_dir/config/.env"

#=================================================
# UPGRADE FUNKWHALE
#=================================================
ynh_script_progression --message="Upgrading Funkwhale..." --weight=1

pushd $install_dir
	source $install_dir/virtualenv/bin/activate

	echo "yes" | ynh_exec_warn_less python api/manage.py collectstatic --clear --noinput

	# needed for enabling the 'unaccent' extension
	ynh_psql_execute_as_root --sql="ALTER USER $db_user WITH SUPERUSER;" --database="$db_name"
	ynh_exec_warn_less python api/manage.py migrate
	ynh_psql_execute_as_root --sql="ALTER USER $db_user WITH NOSUPERUSER;" --database="$db_name"
popd

chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..." --weight=1

ynh_add_config --template="../conf/funkwhale.target" --destination="/etc/systemd/system/$app.target"

# Create a dedicated systemd config
ynh_add_systemd_config --service="${app}-server" --template="funkwhale-server.service"
ynh_add_systemd_config --service="${app}-worker" --template="funkwhale-worker.service"
ynh_add_systemd_config --service="${app}-beat"   --template="funkwhale-beat.service"

#=================================================
# GENERIC FINALIZATION
#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add "${app}-beat"
yunohost service add "${app}-server"
yunohost service add "${app}-worker"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

# Start a systemd service
ynh_systemd_action --service_name="${app}-beat" --action="start" --log_path="systemd" --line_match="Started"
ynh_systemd_action --service_name="${app}-server" --action="start" --log_path="systemd" --line_match="Application startup complete"
ynh_systemd_action --service_name="${app}-worker" --action="start" --log_path="systemd" --line_match="ready"

#=================================================
# UPGRADE FAIL2BAN
#=================================================
ynh_script_progression --message="Reconfiguring Fail2Ban..." --weight=1

# Create a dedicated Fail2Ban config
ynh_add_fail2ban_config --logpath="/var/log/nginx/$domain-access.log" --failregex="<HOST>.* \"POST /api/v1/token/ HTTP/1.1\" 400 68.*$" --max_retry=5

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
